/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BE.BEMaterial;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;

/**
 *
 * @author Claus
 */
public class ChooseMaterialsDialog extends javax.swing.JDialog {

    ArrayList<BEMaterial> Materials;
    ArrayList<BEMaterial> valgteMaterials = new ArrayList<>();
    DefaultListModel alleListModel = new DefaultListModel();
    DefaultListModel valgteListModel = new DefaultListModel();

    /**
     * Populates the Materials ArrayList
     */
    public void InitializeMaterials() {
        try {
            Materials = BLL.BLLMaterial.getInstance().getAll();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    

    public ChooseMaterialsDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        InitializeMaterials();
        setTitle("Materiale Oversigt");
        ActionListener BTNListener = new BTNMoveActionListener();
        ActionListener BTNTilfoejListener = new BTNTilfoejActionListener();
        btnAddToChosenMaterials.addActionListener(BTNListener);
        btnRemoveFromChosenMaterials.addActionListener(BTNListener);
        btnAddMaterials.addActionListener(BTNTilfoejListener);
        jlistAllMaterials.setModel(alleListModel);
        jlistChosenMaterials.setModel(valgteListModel);
        PopulateList();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

/**
 * A function that can move item between lists
 * @param source
 * @param target 
 */    
    private void moveItem(JList source, JList target) {

        int idx = source.getSelectedIndex();
        if (idx == -1) {
            return;
        }
        String element = (String) source.getModel().getElementAt(idx);
        DefaultListModel modelTarget = (DefaultListModel) target.getModel();
        modelTarget.addElement(element);
        DefaultListModel modelSource = (DefaultListModel) source.getModel();
        modelSource.remove(idx);
    }

    /**
     * Returns the chosen materials
     * @return valgteMaterials 
     */
    public ArrayList<BEMaterial> getValgteMaterials() {
        return valgteMaterials;
    }

    /**
     * Actionlistener for Buttons used for moving items between lists
     */
    private class BTNMoveActionListener implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {
            if (e.getSource() == btnAddToChosenMaterials) {
                moveItem(jlistAllMaterials, jlistChosenMaterials);
            } else {
                moveItem(jlistChosenMaterials, jlistAllMaterials);
            }
        }
    }

    /**
     * Actionlistener on Tilfoej Button. Also adds the items on the valgteListModel to the
     * valgteMaterials ArrayList
     */
    private class BTNTilfoejActionListener implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {
            for (int i = 0; i < valgteListModel.getSize(); i++) {
                BEMaterial temp = new BEMaterial((String) jlistChosenMaterials.getModel().getElementAt(i));
                valgteMaterials.add(i, temp);
            }
            dispose();
        }
    }
/**
 * Populates the alleListModel
 */
    private void PopulateList() {
        for (BEMaterial m : Materials) {
            alleListModel.addElement(m.getM_Materiale());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jlistChosenMaterials = new javax.swing.JList();
        jScrollPane1 = new javax.swing.JScrollPane();
        jlistAllMaterials = new javax.swing.JList();
        btnRemoveFromChosenMaterials = new javax.swing.JButton();
        btnAddToChosenMaterials = new javax.swing.JButton();
        lblChosenMaterials = new javax.swing.JLabel();
        btnAddMaterials = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        lblAllMaterials = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jScrollPane2.setViewportView(jlistChosenMaterials);

        jScrollPane1.setViewportView(jlistAllMaterials);

        btnRemoveFromChosenMaterials.setText("Fjern fra Materialer");

        btnAddToChosenMaterials.setText("Føj til Materialer");
        btnAddToChosenMaterials.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddToChosenMaterialsActionPerformed(evt);
            }
        });

        lblChosenMaterials.setText("Valgte Materialer:");

        btnAddMaterials.setText("Tilføj Materialer");
        btnAddMaterials.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddMaterialsActionPerformed(evt);
            }
        });

        btnCancel.setText("Annuller");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        lblAllMaterials.setText("Alle Materialer:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnRemoveFromChosenMaterials))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAddToChosenMaterials, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblAllMaterials)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblChosenMaterials)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCancel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAddMaterials, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(btnAddToChosenMaterials)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRemoveFromChosenMaterials)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblChosenMaterials)
                            .addComponent(lblAllMaterials))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddMaterials)
                    .addComponent(btnCancel))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddToChosenMaterialsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddToChosenMaterialsActionPerformed

    }//GEN-LAST:event_btnAddToChosenMaterialsActionPerformed

    private void btnAddMaterialsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddMaterialsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddMaterialsActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddMaterials;
    private javax.swing.JButton btnAddToChosenMaterials;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnRemoveFromChosenMaterials;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList jlistAllMaterials;
    private javax.swing.JList jlistChosenMaterials;
    private javax.swing.JLabel lblAllMaterials;
    private javax.swing.JLabel lblChosenMaterials;
    // End of variables declaration//GEN-END:variables
}
