/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author Claus
 */
public class FiremanMenu extends javax.swing.JFrame {

    /**
     * Creates new form FiremanMenu
     */
    public FiremanMenu() {
        initComponents();
        setTitle("Brandmand Menu");

        /**
         * All ActionListeners are listed here
         */
        ActionListener BTNEmergencySchedule = new EmergencyScheduleListener();
        btnEmergencySchedule.addActionListener(BTNEmergencySchedule);
        ActionListener BTNTimeSchedule = new TimeScheduleListener();
        btnTimeSchedule.addActionListener(BTNTimeSchedule);
    }

    private class EmergencyScheduleListener implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {
            openEmergencySchedule();
        }
    }

    private class TimeScheduleListener implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {
            openTimeSchedule();
        }

    }

    private void openEmergencySchedule(){
        EmergencyStartDialog EmergencySchedule = new EmergencyStartDialog(this, true, null);
        setLocationRelativeTo(this);
        EmergencySchedule.setVisible(true);
    }
    
    private void openTimeSchedule() {
        Timeplan timePlan = new Timeplan();
        setLocationRelativeTo(this);
        timePlan.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFiremanMenu = new javax.swing.JLabel();
        btnEmergencySchedule = new javax.swing.JButton();
        jPanelUdrykningsSkema = new javax.swing.JPanel();
        lblEmergencyScheduleMenu1 = new javax.swing.JLabel();
        lblEmergencyScheduleMenu2 = new javax.swing.JLabel();
        lblEmergencyScheduleMenu3 = new javax.swing.JLabel();
        btnTimeSchedule = new javax.swing.JButton();
        jPanelTimeSchedule = new javax.swing.JPanel();
        lblTimeScheduleMenu1 = new javax.swing.JLabel();
        lblTimeScheduleMenu2 = new javax.swing.JLabel();
        lblTimeScheduleMenu3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblFiremanMenu.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        lblFiremanMenu.setText("Fireman Menu");

        btnEmergencySchedule.setText("Udryknings Skema");

        jPanelUdrykningsSkema.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblEmergencyScheduleMenu1.setText("- Liste over udrykninger");

        lblEmergencyScheduleMenu2.setText("- Lav timeplan for en udrykning med tidsstempel");

        lblEmergencyScheduleMenu3.setText("- Lav ODIN report for en udrykning med tidsstempel");

        javax.swing.GroupLayout jPanelUdrykningsSkemaLayout = new javax.swing.GroupLayout(jPanelUdrykningsSkema);
        jPanelUdrykningsSkema.setLayout(jPanelUdrykningsSkemaLayout);
        jPanelUdrykningsSkemaLayout.setHorizontalGroup(
            jPanelUdrykningsSkemaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelUdrykningsSkemaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelUdrykningsSkemaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEmergencyScheduleMenu1)
                    .addComponent(lblEmergencyScheduleMenu2)
                    .addComponent(lblEmergencyScheduleMenu3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelUdrykningsSkemaLayout.setVerticalGroup(
            jPanelUdrykningsSkemaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelUdrykningsSkemaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblEmergencyScheduleMenu1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEmergencyScheduleMenu2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEmergencyScheduleMenu3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnTimeSchedule.setText("Udarbejd en report");

        jPanelTimeSchedule.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblTimeScheduleMenu1.setText("- Udarbejdelse af report");

        lblTimeScheduleMenu2.setText("- Lav timeplan uden udryknings tidsstempel");

        lblTimeScheduleMenu3.setText("- Lav ODIN report uden udryknings tidsstempel");

        javax.swing.GroupLayout jPanelTimeScheduleLayout = new javax.swing.GroupLayout(jPanelTimeSchedule);
        jPanelTimeSchedule.setLayout(jPanelTimeScheduleLayout);
        jPanelTimeScheduleLayout.setHorizontalGroup(
            jPanelTimeScheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTimeScheduleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelTimeScheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTimeScheduleMenu1)
                    .addComponent(lblTimeScheduleMenu2)
                    .addComponent(lblTimeScheduleMenu3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelTimeScheduleLayout.setVerticalGroup(
            jPanelTimeScheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTimeScheduleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTimeScheduleMenu1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTimeScheduleMenu2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTimeScheduleMenu3)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblFiremanMenu)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnTimeSchedule, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                            .addComponent(btnEmergencySchedule, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanelUdrykningsSkema, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelTimeSchedule, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFiremanMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEmergencySchedule)
                    .addComponent(jPanelUdrykningsSkema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTimeSchedule)
                    .addComponent(jPanelTimeSchedule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FiremanMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FiremanMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FiremanMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FiremanMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FiremanMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEmergencySchedule;
    private javax.swing.JButton btnTimeSchedule;
    private javax.swing.JPanel jPanelTimeSchedule;
    private javax.swing.JPanel jPanelUdrykningsSkema;
    private javax.swing.JLabel lblEmergencyScheduleMenu1;
    private javax.swing.JLabel lblEmergencyScheduleMenu2;
    private javax.swing.JLabel lblEmergencyScheduleMenu3;
    private javax.swing.JLabel lblFiremanMenu;
    private javax.swing.JLabel lblTimeScheduleMenu1;
    private javax.swing.JLabel lblTimeScheduleMenu2;
    private javax.swing.JLabel lblTimeScheduleMenu3;
    // End of variables declaration//GEN-END:variables
}
