/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BLL.BLLFireman;
import BLL.BLLPayroll;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Claus
 */
public class PayrollDetails extends javax.swing.JDialog {

    DefaultListModel salaryListModel = new DefaultListModel();
    private final String SalaryNumber;
    ArrayList<BE.BESalary> allSalarys = new ArrayList<>();

    /**
     * Creates new form AddFiremanDialog
     *
     * @param parent
     * @param modal
     * @param SalaryNumber
     * @throws java.lang.Exception
     */
    public PayrollDetails(java.awt.Frame parent, boolean modal, String SalaryNumber) throws Exception {
        super(parent, modal);
        initComponents();
        this.SalaryNumber = SalaryNumber;
        setTitle("Detaljer for salaryReports");
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        salaryListModelRenewal();
        lblLeadertrained.setVisible(false);
        lstSalaryRapport.setModel(salaryListModel);
        btnUpdate.setEnabled(false);
        txtDate.setEnabled(false);
        txtFiremanName.setEnabled(false);
        txtOdinNr.setEnabled(false);
        txtRole.setEnabled(false);
        lstSalaryRapport.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                filldata();
                btnUpdate.setEnabled(true);

            }
        });
    }

    /**
     *
     */
    private void filldata() {
        try {
            BLLFireman g = new BLLFireman();
            if (allSalarys.get(lstSalaryRapport.getSelectedIndex()).getODIN() != 0) {
                txtOdinNr.setText(Integer.toString(allSalarys.get(lstSalaryRapport.getSelectedIndex()).getODIN()));
            } else {
                txtOdinNr.setText(Integer.toString(allSalarys.get(lstSalaryRapport.getSelectedIndex()).getWORK()));
            }
            BE.BEFireman f = g.FiremanFromID(allSalarys.get(lstSalaryRapport.getSelectedIndex()).getFiremanID());
            txtFiremanName.setText(f.getFirstName() + " " + f.getLastName());
            txtRole.setText(allSalarys.get(lstSalaryRapport.getSelectedIndex()).getRole());
            txtDate.setText(allSalarys.get(lstSalaryRapport.getSelectedIndex()).getDate());
            txtHours.setText(Double.toString(allSalarys.get(lstSalaryRapport.getSelectedIndex()).getHours()));
            lblLeadertrained.setVisible(g.FiremanFromID(allSalarys.get(lstSalaryRapport.getSelectedIndex()).getFiremanID()).isLeaderTrained());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnback = new javax.swing.JButton();
        scrollPnlSalaryReport = new javax.swing.JScrollPane();
        lstSalaryRapport = new javax.swing.JList();
        jPanelInformation = new javax.swing.JPanel();
        lblRole = new javax.swing.JLabel();
        txtFiremanName = new javax.swing.JTextField();
        txtOdinNr = new javax.swing.JTextField();
        lblOdinNr = new javax.swing.JLabel();
        lblFiremanName = new javax.swing.JLabel();
        txtRole = new javax.swing.JTextField();
        lblHours = new javax.swing.JLabel();
        txtHours = new javax.swing.JTextField();
        lblDate = new javax.swing.JLabel();
        txtDate = new javax.swing.JTextField();
        lblLeadertrained = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnback.setText("Luk Vindue");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });

        scrollPnlSalaryReport.setViewportView(lstSalaryRapport);

        jPanelInformation.setBorder(javax.swing.BorderFactory.createTitledBorder("Information"));

        lblRole.setText("Rolle");

        lblOdinNr.setText("Odin Nr:");

        lblFiremanName.setText("Brandmand Navn");

        lblHours.setText("Timer");

        lblDate.setText("Dato");

        lblLeadertrained.setText("Personen er Holdleder uddannet");

        javax.swing.GroupLayout jPanelInformationLayout = new javax.swing.GroupLayout(jPanelInformation);
        jPanelInformation.setLayout(jPanelInformationLayout);
        jPanelInformationLayout.setHorizontalGroup(
            jPanelInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInformationLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanelInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLeadertrained)
                    .addComponent(lblFiremanName)
                    .addComponent(lblOdinNr)
                    .addComponent(lblRole)
                    .addGroup(jPanelInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtOdinNr, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtFiremanName, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblDate, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblHours, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtHours, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                        .addComponent(txtDate, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtRole, javax.swing.GroupLayout.Alignment.LEADING))))
        );
        jPanelInformationLayout.setVerticalGroup(
            jPanelInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInformationLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblOdinNr)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtOdinNr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblFiremanName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFiremanName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblRole)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(lblLeadertrained)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblDate)
                .addGap(6, 6, 6)
                .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblHours)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtHours, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        btnUpdate.setText("Opdater");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(scrollPnlSalaryReport, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnUpdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnback))
                    .addComponent(jPanelInformation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelInformation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnback)
                            .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(scrollPnlSalaryReport))
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        dispose();
    }//GEN-LAST:event_btnbackActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        try {
            double timer = Double.parseDouble(txtHours.getText());
            try {
                BE.BESalary s = allSalarys.get(lstSalaryRapport.getSelectedIndex());
                s.setHours(timer);
                BLLPayroll pay = new BLLPayroll();
                pay.update(s);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Du må kun intaste nummre i timer.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnback;
    private javax.swing.JPanel jPanelInformation;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblFiremanName;
    private javax.swing.JLabel lblHours;
    private javax.swing.JLabel lblLeadertrained;
    private javax.swing.JLabel lblOdinNr;
    private javax.swing.JLabel lblRole;
    private javax.swing.JList lstSalaryRapport;
    private javax.swing.JScrollPane scrollPnlSalaryReport;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtFiremanName;
    private javax.swing.JTextField txtHours;
    private javax.swing.JTextField txtOdinNr;
    private javax.swing.JTextField txtRole;
    // End of variables declaration//GEN-END:variables

    private void salaryListModelRenewal() throws Exception {
        allSalarys.clear();
        BLLPayroll p = new BLLPayroll();
        for (BE.BESalary s : p.getAll()) {
            if (SalaryNumber.equalsIgnoreCase(s.getSalaryCode().trim())) {
                allSalarys.add(s);
                if (s.getODIN() != 0) {
                    salaryListModel.addElement(s.getODIN() + "-" + BLL.BLLTimePlan.getInstance().getTypeOfWorkFromInt(s.getTypeOfWork()));
                } else {
                    salaryListModel.addElement(s.getWORK() + "-" + BLL.BLLTimePlan.getInstance().getTypeOfWorkFromInt(s.getTypeOfWork()));
                }
            }
        }
    }
}
