/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BE.BEMaterial;
import BE.BETimePlan;
import BLL.BLLTimePlan;
import java.util.ArrayList;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Claus
 */
public class Timeplan extends javax.swing.JFrame {

    TimePlanTableModel TimeTableModel;
    TableRowSorter<TableModel> sorter;
    ArrayList<BETimePlan> allTime = new ArrayList<>();
    BLLTimePlan MyBLLTimePlan = new BLLTimePlan();

//    private void initTimePlan() {
//        allTime = MyBLLTimePlan.getAll();
//    }

    /**
     * Creates new form Timeplan
     */
    public Timeplan() {
        initComponents();
       // initTimePlan();
        TimeTableModel = new TimePlanTableModel(allTime);
        jtableTeamTabel.setModel(TimeTableModel);// Sets the table model for the JTable
        sorter = new TableRowSorter<TableModel>(TimeTableModel);
        jtableTeamTabel.setRowSorter(sorter);
        jtableTeamTabel.getTableHeader().setReorderingAllowed(false);
        txtAndetTekst.setVisible(false);
        setTitle("Udryknings Skema");
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbTypeIndsats = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtableTeamTabel = new javax.swing.JTable();
        txtAndetTekst = new javax.swing.JTextField();
        btnVaelgTeam = new javax.swing.JButton();
        btnNaesteSide = new javax.swing.JButton();
        btnLukVindue = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cmbTypeIndsats.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Indsats", "Øvelse", "Brandvagt", "Stand-By", "Arbejde Falck", "Følgeskadeindsats", "Andet" }));
        cmbTypeIndsats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTypeIndsatsActionPerformed(evt);
            }
        });

        jtableTeamTabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jtableTeamTabel);

        btnVaelgTeam.setText("Vælg Team");
        btnVaelgTeam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVaelgTeamActionPerformed(evt);
            }
        });

        btnNaesteSide.setText("Næste Side");
        btnNaesteSide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNaesteSideActionPerformed(evt);
            }
        });

        btnLukVindue.setText("Luk Vindue");
        btnLukVindue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLukVindueActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 521, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cmbTypeIndsats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAndetTekst)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnVaelgTeam, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnLukVindue, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNaesteSide, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbTypeIndsats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAndetTekst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVaelgTeam))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNaesteSide)
                    .addComponent(btnLukVindue))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVaelgTeamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVaelgTeamActionPerformed
        ChooseTeam chooseTeam = new ChooseTeam(this, true);
        chooseTeam.setVisible(true);
        chooseTeam.setLocationRelativeTo(this);

        // continue here when the dialog box is closed (disposed).
        ArrayList<BETimePlan> plan = chooseTeam.getTeam();
        if (plan != null) // a team has been created in the dialog box.
        {
            if (!allTime.isEmpty()) {
                for (int i = 0; i < plan.size(); i++) {
                    allTime.add(plan.get(i));
                }
            } else {
                allTime = plan;
            }
            //jtableTeamTabel.setModel(MaterialModel);
            //jtableMaterialer1.setRowSorter(sorter);
            //jtableMaterialer1.getTableHeader().setReorderingAllowed(false);

            TimeTableModel.setTimePlanStatusList(allTime);
            jtableTeamTabel.repaint();
        }
    }//GEN-LAST:event_btnVaelgTeamActionPerformed

    private void btnLukVindueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLukVindueActionPerformed
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnLukVindueActionPerformed

    private void btnNaesteSideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNaesteSideActionPerformed
        dispose();
        ODINReport odinReport = new ODINReport();
        odinReport.setVisible(true);
        odinReport.setLocationRelativeTo(this);
    }//GEN-LAST:event_btnNaesteSideActionPerformed

    private void cmbTypeIndsatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTypeIndsatsActionPerformed
 if(cmbTypeIndsats.getSelectedItem().toString().equalsIgnoreCase("Andet")){
     txtAndetTekst.setVisible(true);
 }
     else
     txtAndetTekst.setVisible(false);
 
    }//GEN-LAST:event_cmbTypeIndsatsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLukVindue;
    private javax.swing.JButton btnNaesteSide;
    private javax.swing.JButton btnVaelgTeam;
    private javax.swing.JComboBox cmbTypeIndsats;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtableTeamTabel;
    private javax.swing.JTextField txtAndetTekst;
    // End of variables declaration//GEN-END:variables
}
