/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BE.BETimePlan;
import BLL.BLLPDF;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.JOptionPane;

import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Peter
 */
public class Timeplan extends javax.swing.JFrame {

    TimePlanTableModel TimeTableModel;
    TableRowSorter<TableModel> sorter;
    ArrayList<BETimePlan> allTime = new ArrayList<>();
    ArrayList<String> colNames;
    String type;
    private PDFListener PDFListener; // holds a reference to a class that implements PDFListener
    BLLPDF BLLPDF = new BLLPDF();

    /**
     * Creates new form Timeplan
     */
    public Timeplan() {
        initComponents();
        setPDFListener(BLLPDF); // sets the BLLPDF as observer
        TimeTableModel = new TimePlanTableModel(allTime);
        jtableTeamTabel.setModel(TimeTableModel);// Sets the table model for the JTable
        sorter = new TableRowSorter<TableModel>(TimeTableModel);
        jtableTeamTabel.setRowSorter(sorter);
        jtableTeamTabel.getTableHeader().setReorderingAllowed(false);
        txtAndetTekst.setEnabled(false);
        setTitle("Udryknings Skema");
        setLocationRelativeTo(null);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);

        /**
         * All ActionListeners are listed here
         */
        ActionListener BTNPDFListener = new BTNPDFActionListener();
        ActionListener BTNChooseTeam = new ChooseTeamListener();
        ActionListener BTNClose = new CloseListener();
        ActionListener CMBBOXType = new CMBBoxListener();
        btnNextPage.addActionListener(BTNPDFListener);
        btnVaelgTeam.addActionListener(BTNChooseTeam);
        btnLukVindue.addActionListener(BTNClose);
        cmbTypeIndsats.addActionListener(CMBBOXType);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbTypeIndsats = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtableTeamTabel = new javax.swing.JTable();
        btnVaelgTeam = new javax.swing.JButton();
        btnLukVindue = new javax.swing.JButton();
        btnNextPage = new javax.swing.JButton();
        txtAndetTekst = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cmbTypeIndsats.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Indsats", "Øvelse", "Brandvagt", "Stand-By", "Arbejde Falck", "Følgeskadeindsats", "Andet" }));

        jtableTeamTabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jtableTeamTabel);

        btnVaelgTeam.setText("Vælg Team");

        btnLukVindue.setText("Luk Vindue");

        btnNextPage.setText("Næste side");

        txtAndetTekst.setMinimumSize(new java.awt.Dimension(290, 23));
        txtAndetTekst.setPreferredSize(new java.awt.Dimension(290, 23));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnLukVindue, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNextPage, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(cmbTypeIndsats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtAndetTekst, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnVaelgTeam, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVaelgTeam)
                    .addComponent(cmbTypeIndsats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAndetTekst, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLukVindue)
                    .addComponent(btnNextPage))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private class CMBBoxListener implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {
            if (cmbTypeIndsats.getSelectedItem().equals("Andet")) {
                txtAndetTekst.setEnabled(true);
                type = (String) cmbTypeIndsats.getSelectedItem();
            } else {
                txtAndetTekst.setEnabled(false);
                type = (String) cmbTypeIndsats.getSelectedItem();
            }

        }

    }

    private class CloseListener implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {
            dispose();
        }

    }

    private class ChooseTeamListener implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {
            ChooseTeam chooseTeam = new ChooseTeam(Timeplan.this, true);
            chooseTeam.setVisible(true);
            chooseTeam.setLocationRelativeTo(null);

            // continue here when the dialog box is closed (disposed).
            ArrayList<BETimePlan> plan = chooseTeam.getTeam();
            if (plan != null) // a team has been created in the dialog box.
            {
                if (!allTime.isEmpty()) { // checks if there already is entries in the time plan arraylist 
                    for (int i = 0; i < plan.size(); i++) {
                        allTime.add(plan.get(i));
                    }
                } else {
                    allTime = plan;
                }

                TimeTableModel.setTimePlanStatusList(allTime);
                jtableTeamTabel.repaint();
            }
        }

    }

    /**
     * anonymous inner class listening on the create pdf button
     */
    private class BTNPDFActionListener implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {
            getColNames();
            firePDFEvent(new FormatEventPDF(allTime, colNames, type));
        }
    }

    /**
     * Fires a PDF event
     *
     * @param event type FormatEventPDF
     */
    public void firePDFEvent(FormatEventPDF event) {
        if (PDFListener != null) {
            try {
                PDFListener.PDFTimePlanPerformed(event);
                JOptionPane.showMessageDialog(null, "Timeplan blev gemt", "Færdig", JOptionPane.INFORMATION_MESSAGE);
            } catch (EventExercutionException eex) {
                JOptionPane.showMessageDialog(null, eex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        dispose();
        ODINReport report = new ODINReport();
        report.setVisible(true);
        report.setLocationRelativeTo(this);
    }

    private void getColNames() {
        colNames = new ArrayList<>();
        for (int i = 0; i < TimeTableModel.getColumnCount(); i++) {
            colNames.add(TimeTableModel.getColumnName(i));
        }
    }

    public void setPDFListener(PDFListener PDFListener) {
        this.PDFListener = PDFListener;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLukVindue;
    private javax.swing.JButton btnNextPage;
    private javax.swing.JButton btnVaelgTeam;
    private javax.swing.JComboBox cmbTypeIndsats;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtableTeamTabel;
    private javax.swing.JTextField txtAndetTekst;
    // End of variables declaration//GEN-END:variables
}
